### ISSUE TITLE
[BUG] Memoryleak

### ISSUE THREAD

**Issue by Alphacharge** [Sangyao42/get_next_line#1]
Your gnl is leaking if a Programm doesn't read all lines from a file.
You could use memcpy instead of strdup to fill the static with the rest. For this you have to change the static to an array[Buffersize] instead of a pointer.

**Comment by Sangyao42** [comment]
I have a modified version using static char[BUF + 1] in the branch gnl_new. :)
Now the data is located at data section in the memory. I was told this solution is not thread save, because we don't have mutex lock on this static variable.
But with memory allocation, valgrind checked also "still reachable" memory, which means the developer can free it somewhere else in the program. However, I did not find the solution in the case of gnl. Do you have any suggestion?

**Comment by Alphacharge** [comment]
No Leak anymore if you don't read every line of a file.
`root@b5d14bebaf91:code#gcc -Wall -Wextra -Werror get_next_line.c main_gnl.c get_next_line_utils.c get_next_line.h
root@b5d14bebaf91:code#valgrind --leak-check=full ./a.out
==48== Memcheck, a memory error detector
==48== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==48== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==48== Command: ./a.out
==48==
/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   get_next_line.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
==48==
==48== HEAP SUMMARY:
==48==     in use at exit: 0 bytes in 0 blocks
==48==   total heap usage: 16 allocs, 16 frees, 10,634 bytes allocated
==48==
==48== All heap blocks were freed -- no leaks are possible
==48==
==48== For lists of detected and suppressed errors, rerun with: -s
==48== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)`
